spring:
  data:
    mongodb:
      database: test
      uri: mongodb://127.0.0.1:27017

# For future purposes
app:
  auth:
    basic:
      username: manuel.gozzi
      password: AjkD123!#@_d351KlK01,